name: Deploy to Vercel on PR

on:
  push:
    branches-ignore:
      - main # mainブランチ以外にプッシュされたときにデプロイを実行

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用する仮想環境

    steps:
      # 1. コードのチェックアウト
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Node.jsのセットアップ
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0' # 使用するNode.jsのバージョン

      # 3. キャッシュの削除
      - name: Clear Cache
        run: |
          rm -rf node_modules/.cache
          npm cache clean --force

      # 4. 依存関係のインストール
      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps

      # 5. Vercel CLIのインストール
      - name: Install Vercel CLI
        run: |
          npm install -g vercel

      # 6. Vercelへのデプロイ
      - name: Deploy to Vercel
        run: |
          echo 'VERCEL_RESPONSE=$(vercel --token ${{ secrets.VERCEL_TOKEN }} --confirm)' >> $GITHUB_ENV

      - name: Comment to PR
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "$VERCEL_RESPONSE"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}